config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only [:new, :create]
  end
  resources :doses, only[:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy ]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update

  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :dose)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:show, :edit, :update, :destroy ]

  def index
    @doses = Dose.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredients = Ingredient.all - @cocktail.ingredients
    @dose = Dose.new
  end

  def create
    raise
    cocktail_id = params[:cocktail_id]
    ingredient_id = params[:dose][:ingredient_id]
    @cocktail = Cocktail.find(cocktail_id)
    @dose = Dose.new(dose_params)

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<h1>Edit <%= @cocktail.name %></h1>

<%= link_to "Add Dose", new_cocktail_dose_path(@cocktail) %>
edit.html.erb

app/views/cocktails/index.html.erb
<h1>cocktails#index</h1>
<!-- show all cocktails  -->
<%= link_to "Create", new_cocktail_path, class: "btn btn-primary" %>
<ul>
  <% @cocktails.each do |cocktail| %>
    <li>
      <p>
        <%= link_to cocktail.name, cocktail_path(cocktail) %>
        <%= link_to "", cocktail_path(cocktail), method: :delete, class: "fa fa-times"  %>
      </p>
    </li>
  <% end %>
</ul>

app/views/cocktails/new.html.erb
<h1>Create new Cocktail Recipe</h1>
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<h1>cocktails#show</h1>
<h1><%= @cocktail.name %></h1>

<!-- show all doses -->

<p>
  <%= link_to "Add dose", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
</p>
<%= link_to "Edit", edit_cocktail_path(@cocktail), class: "btn btn-warning" %>
<%= link_to "Delete", cocktail_path(@cocktail), method: :delete, class: "btn btn-danger" %>

app/views/doses/index.html.erb
<h1>doses#index</h1>

app/views/doses/new.html.erb
<h1>Add Dose to <%= @cocktail.name %></h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description, placeholder: "Quantity", label: false %>
  <%= f.input :ingredient_id, collection: @ingredients, include_blank: false, prompt: "Please select an ingredient", label: false %>
  <%= f.submit %>
<% end %>

<!-- prompt: "Please select an ingredient" -->

app/views/doses/show.html.erb
<h1>doses#show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row text-center">
        <%= yield %>
      </div>
    </div>
  </body>
</html>